# Generated by Django 4.1 on 2023-08-06 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0003_rename_is_admin_user_is_staff_remove_user_is_active"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserImage",
        ),
    ]
