# Generated by Django 4.1 on 2023-08-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0004_delete_userimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
