# Generated by Django 4.1 on 2023-08-02 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("UserBookLike", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbooklike",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_book_like",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
