# Generated by Django 4.1 on 2023-08-08 09:33

import Book.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookInfo",
            fields=[
                ("book_id", models.AutoField(primary_key=True, serialize=False)),
                ("book_name", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=20)),
                ("is_popular", models.BooleanField(default=False)),
                ("publication_year", models.CharField(max_length=20)),
                (
                    "book_status",
                    models.CharField(
                        choices=[("기증도서", "기증도서"), ("저작권 만료도서", "저작권 만료도서")],
                        default="기증도서",
                        max_length=20,
                        verbose_name="기증 / 만료 여부",
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                ("like", models.PositiveIntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mainCategory",
                    models.ForeignKey(
                        blank=True,
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="mainCategory",
                        to="Category.category",
                        validators=[Book.models.main_category_validator],
                    ),
                ),
                (
                    "subCategory",
                    models.ForeignKey(
                        blank=True,
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="subCategory",
                        to="Category.category",
                        validators=[Book.models.sub_category_validator],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookFile",
            fields=[
                ("file_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "page_image",
                    models.ImageField(upload_to=Book.models.upload_book_page_path),
                ),
                ("page_num", models.PositiveIntegerField(default=0)),
                (
                    "book_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Book.bookinfo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookCover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_cover",
                    models.ImageField(upload_to=Book.models.upload_book_cover_path),
                ),
                (
                    "book_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="Book.bookinfo"
                    ),
                ),
            ],
        ),
    ]
