# Generated by Django 4.1 on 2023-08-09 06:50

import Book.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Category", "0001_initial"),
        ("Book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinfo",
            name="subCategory",
            field=models.ForeignKey(
                blank=True,
                default=4,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="subCategory",
                to="Category.category",
                validators=[Book.models.sub_category_validator],
            ),
        ),
    ]
