# Generated by Django 4.1 on 2023-07-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Book", "0002_bookinfo_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookcover",
            name="book_cover",
            field=models.ImageField(upload_to="media/bookCover/"),
        ),
        migrations.AlterField(
            model_name="bookfile",
            name="book_file",
            field=models.FileField(upload_to="media/bookFile/"),
        ),
    ]
