# Generated by Django 4.1 on 2023-08-09 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Book", "0002_alter_bookinfo_subcategory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookfile",
            old_name="page_num",
            new_name="page",
        ),
    ]
