# Generated by Django 4.1 on 2023-08-08 08:32

import Book.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Book", "0003_alter_bookinfo_maincategory_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookinfo",
            old_name="book_Name",
            new_name="book_name",
        ),
        migrations.RemoveField(
            model_name="bookfile",
            name="book_file",
        ),
        migrations.RemoveField(
            model_name="bookinfo",
            name="publication_month",
        ),
        migrations.AddField(
            model_name="bookfile",
            name="page_image",
            field=models.ImageField(
                default=None, upload_to=Book.models.upload_book_page_path
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookfile",
            name="page_num",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bookinfo",
            name="average_rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="bookinfo",
            name="book_status",
            field=models.CharField(
                choices=[("기증도서", "기증도서"), ("저작권 만료도서", "저작권 만료도서")],
                default="기증도서",
                max_length=20,
                verbose_name="기증 / 만료 여부",
            ),
        ),
        migrations.AddField(
            model_name="bookinfo",
            name="like",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bookinfo",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bookcover",
            name="book_cover",
            field=models.ImageField(upload_to=Book.models.upload_book_cover_path),
        ),
        migrations.AlterField(
            model_name="bookfile",
            name="book_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Book.bookinfo"
            ),
        ),
        migrations.DeleteModel(
            name="BookStats",
        ),
    ]
