# Generated by Django 4.1 on 2023-08-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Book", "0003_rename_page_num_bookfile_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinfo",
            name="book_introduction",
            field=models.TextField(default="Sample Introduction"),
            preserve_default=False,
        ),
    ]
