# Generated by Django 4.1 on 2023-08-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Book", "0004_rename_book_name_bookinfo_book_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookfile",
            name="id",
        ),
        migrations.AddField(
            model_name="bookfile",
            name="file_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
