# Generated by Django 4.1 on 2023-07-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Book", "0004_alter_bookinfo_maincategory_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookstats",
            old_name="rating",
            new_name="average_rating",
        ),
        migrations.AddField(
            model_name="bookstats",
            name="rating_count",
            field=models.IntegerField(default=0),
        ),
    ]
