# Generated by Django 4.1 on 2023-08-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annotation", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="AnnotationInfo",
            fields=[
                ("annotation_id", models.AutoField(primary_key=True, serialize=False)),
                ("annotation_num", models.IntegerField(default=1)),
                ("page", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
