# Generated by Django 4.1 on 2023-08-01 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Book", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotationInfo",
            fields=[
                ("annotation_id", models.AutoField(primary_key=True, serialize=False)),
                ("annotation_num", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Book.bookinfo"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annotation", models.TextField()),
                (
                    "annotation_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Annotation.annotationinfo",
                    ),
                ),
            ],
        ),
    ]
