# Generated by Django 4.1 on 2023-08-03 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Book", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Annotation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationinfo",
            name="page",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="annotationinfo",
            name="annotation_num",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="annotationinfo",
            name="book_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_annotation",
                to="Book.bookinfo",
            ),
        ),
        migrations.AlterField(
            model_name="annotationinfo",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_annotation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
