# Generated by Django 4.1 on 2023-08-08 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Annotation", "0001_initial"),
        ("Book", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationinfo",
            name="book_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_annotation",
                to="Book.bookinfo",
            ),
        ),
        migrations.AddField(
            model_name="annotationinfo",
            name="file_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_annotation",
                to="Book.bookfile",
            ),
        ),
        migrations.AddField(
            model_name="annotationinfo",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_annotation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="annotation_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotation",
                to="Annotation.annotationinfo",
            ),
        ),
    ]
