# Generated by Django 4.1 on 2023-08-04 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Annotation", "0002_annotationinfo_page_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="annotation_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotation",
                to="Annotation.annotationinfo",
            ),
        ),
    ]
