# Generated by Django 4.1 on 2023-08-04 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Comment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentinfo",
            name="parentComment_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Comment.commentinfo",
            ),
        ),
    ]
