# Generated by Django 4.1 on 2023-08-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Category", "0002_alter_category_category_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
