# Generated by Django 4.1 on 2023-07-30 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Category", "0002_category_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="mainCategory_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Category.category",
                unique=True,
            ),
        ),
    ]
