# Generated by Django 4.1 on 2023-08-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Category", "0004_alter_category_maincategory_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
